### ISSUE TITLE
Exception running the builder

### ISSUE THREAD

**Issue by marcospassos** [switchtrue/JIRAChangelogBuilder#19]
I'm facing the following exception running the lasted release of the changelog builder:

```
java -jar jira-changelog-builder.jar http://192.168.56.110:8080 **** **** Project 0.0.1 ./ plain-text.mustache.txt --debug
DEBUG 10:26:17: --debug flag found. Debug logging enabled.
DEBUG 10:26:17: Starting with parameters: 
  Version: 0.0.1
  JIRA Project Key: Project
  JIRA URL: http://192.168.56.110:8080
  JIRA username: ******
  JIRA password: *******
  Template files: plain-text.mustache.txt
DEBUG 10:26:17: Establishing JIRA API connection for generating changelog to http://192.168.56.110:8080.
DEBUG 10:26:18: Obtaining project information via JIRA API.
Dez 04, 2013 10:26:18 AM com.sun.jersey.api.client.ClientResponse getEntity
Grave: A message body reader for Java class java.lang.String, and Java type class java.lang.String, and MIME media type application/json;charset=UTF-8 was not found
Dez 04, 2013 10:26:18 AM com.sun.jersey.api.client.ClientResponse getEntity
Grave: The registered message body readers compatible with the MIME media type are:
application/json;charset=UTF-8 ->
  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$App
  com.sun.jersey.json.impl.provider.entity.JSONArrayProvider$App
  com.sun.jersey.json.impl.provider.entity.JSONObjectProvider$App
  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$App
  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$App
*/* ->
  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONArrayProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONObjectProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy

Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class java.lang.String, and Java type class java.lang.String, and MIME media type application/json;charset=UTF-8 was not found
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:548)
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:505)
    at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.invoke(AbstractJerseyRestClient.java:66)
    at com.atlassian.jira.rest.client.internal.jersey.JerseyProjectRestClient.getProject(JerseyProjectRestClient.java:49)
    at com.atlassian.jira.rest.client.internal.jersey.JerseyProjectRestClient.getProject(JerseyProjectRestClient.java:63)
    at net.foxopen.jira.changelog.JiraAPI.fetchVersionDetails(JiraAPI.java:99
```

**Comment by marcospassos** [comment]
The problem is that I'm using the project name, as mentioned in the documentation, instead of the project key. I'm opening a pull request which address it.

**Comment by switchtrue** [comment]
Pull request has been merged.
